<a href="https://colab.research.google.com/github/maevemdeegan/maevemdeegan/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy

NumPy is a Python library which contains support for matrices and mathematical operations on matrices.

It is fundamental to most applications of Python in the sciences -- many other libraries build upon the NumPy functionality.

If you have NumPy installed on the computer that you are working on, you can import it as follows:

In [ ]:
import numpy as np

## arrays

The fundamental data type of NumPy is `array` (sometimes known as `ndarray`), which is a type for _homogeneous_ $n$-dimensional arrays of elements. That they are homogeneous means that all the elements in an array have the same type. This is in contrast to lists and tuples in Python.

An array is created with the `np.array()` function, where you give a list of the elements of the array as an argument. If the array you wish to create is a 1D array, it's just a list of the numbers; if it is a 2D array, then you give a list of the rows (where each row is also a list of numbers), etc.

In [ ]:
# example of creating 1D, 2D and 3D arrays.
# first a 1D
a1 = np.array([1, -2, 0, 6])
print(a1)

[ 1 -2  0  6]


In [ ]:
# Then a 2D
a2 = np.array([[2,3,-1],[5,0, -4]])
print(a2)

[[ 2  3 -1]
 [ 5  0 -4]]


In [ ]:
# lastly a 3D - we'll stop here
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


The standard Python collection datatypes, like *lists*, *tuples* and *dictionaries* are heterogeneous, meaning that the elemnents in them does not have to have the same type. You can have a list with numbers, strings and booleans in it. Numpy arrays on the other hand are *homogeneous*, in that the elements must have the same type. If you provide elements of different types to `np.array()`, then a "least common denominator" will be found.

In [ ]:
# lists can be heterogeneous
mylist =  [1, -2, "Galway", 3.1415]
print(mylist)
print(type(mylist))

[1, -2, 'Galway', 3.1415]
<class 'list'>


In [ ]:
# arrays must be homogeneous so myarr will be an array of strings
myarr = np.array(mylist)
print(myarr)
print(type(myarr))

['1' '-2' 'Galway' '3.1415']
<class 'numpy.ndarray'>


### Creating Arrays

Even though we can construct any array we like just by using the `np.array()` function, there are some convenience functions that we can use to more compactly construct arrays.

1. `np.zeros()` constructs a matrix where all entries are zero.
2. `np.ones()` a matrix where all entries are equal to one.
3. `np.empty()` a matrix where the entries are initially unspecified.
4. `np.arange()` the entries are a range of elements
5. `np.linspace()` the entries are linearly spaced in an interval

Some examples of array creation of different dimensions

In [ ]:
# a 2x2 with zeroes.
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# a 3x3 with ones
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# an 'empty' array
np.empty((2,4))

array([[6.90098406e-310, 4.64923216e-310, 0.00000000e+000,
        0.00000000e+000],
       [4.64908058e-310, 4.82337433e+228, 6.14415221e-144,
        1.16097020e-028]])

In [ ]:
# an array whose entries are 1,2,3,...20
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# an array whose entries are 0.0, 0.01, 0.02, ..., 0.20
np.linspace(0.0, 0.20, 21)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ])

### dtype

The type of the elements in an array can be accessed through the **attribute** `dtype`.

In [ ]:
#  of ints and floats and booleans
# the array a2 from above
print(a2)
a2.dtype

[[ 2  3 -1]
 [ 5  0 -4]]


dtype('int64')

In [ ]:
# next the "evenly spaced numbers between 0.0 and 0.2"
np.linspace(0.0, 0.20, 21).dtype

dtype('float64')

In [ ]:
# the array with strings
print(myarr)
myarr.dtype # "<U21" should be interpreted as "unicode strings"

['1' '-2' 'Galway' '3.1415']


dtype('<U21')

### Attributes of arrays

Three important attributes are

1. `ndim` The dimension, or number of axes, of an array.
2. `size` The number of elements in the array.
3. `shape` The number of elements along each dimension.

In [ ]:
# ndim
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
# size
a1.size
a2.size

6

In [ ]:
# shape
a3.shape

(2, 2, 2)